### PR TITLE
Initial Linux and MacOS support

### PR DESCRIPTION
**Pull request by Kalmat**
Initial Linux and MacOS support, which is able to pass tests OK. Please let me know your comments/suggestions/issues.

### CODE REVIEW

**Comment by jsa34** [comment]
This would be great - I am just starting a cross-platform application that needs Linux support, too!  Just to add some moral support for this MR :)

**Comment by Kalmat** [comment]
HAHAHAHA! I definitely thank you. I was on the brink of giving up, since the author is not responding, so I don't know what to do next! My code probably needs some tests in "real world" cases, but I think it would be a shame to waste all that work which could be useful for others (at least as a starting point)... Let's hope Al can answer soon. Otherwise, if you need it, you can download the code from here: https://github.com/Kalmat/PyGetWindow, so you can test/use it and let me know your comments!!!

**Comment by macdeport** [comment]
I can test the MacOS branch if I have the instructions, as I am at this moment ignorant in the use of GitHub ;-)

**Comment by Kalmat** [comment]
Wow!! That would be really nice! Thank you so much. Unfortunately I am not a GitHub expert either... sorry. Could you try to download the code from here? https://github.com/Kalmat/PyGetWindow, I guess then you can use/test it, right?

**Comment by macdeport** [comment]
Here's the test result:
[Unix Script Output.log.zip](https://github.com/asweigart/PyGetWindow/files/6875938/Unix.Script.Output.log.zip)
You are welcome

**Comment by Kalmat** [comment]
Thank you!!! The log seems empty, right? Besides, I thought the tests were
going to be made on MacOS, but the file is called "Unix"... Did you run de
script "test_pygetwindow.py"? In both, Python 2 and 3?

Thanks again for your help!

**Comment by macdeport** [comment]
Totally sorry for this unintentionally empty file and here is the good test file...
[test_pygetwindow_macos.log.zip](https://github.com/asweigart/PyGetWindow/files/6877561/test_pygetwindow_macos.log.zip)

**Comment by Kalmat** [comment]
Thx again!!! I see it fails!!! It didn't on a virtualbox environment... Did you see any window opening? Did you see that window in fullscreen mode (I guess it didn't)? Can I know your MacOS characteristics (OS version, screen resolution, ...). If you have any Python knowledge, I would really appreciate if you can debug/investigate a little further... Unfortunately I don't have acces to a real MacOS and, as I said before, it was working OK on a virtualbox guest.

**Comment by Kalmat** [comment]
This is what happens on my virtualbox MacOS guest (High Sierra)... it's
100% OK! Totally lost here, sorry...
https://drive.google.com/file/d/18bo-oy_u0Klv_SGGkvySSy1ZPym74wbB/view?usp=sharing

**Comment by macdeport** [comment]
> Did you see any window opening? 

Yes, as result of execution of
`subprocess.Popen(['open', '-a', 'TextEdit'])`

> Did you see that window in fullscreen mode (I guess it didn't)?

No, because
`npw.maximize(wait=wait)`
fails

This maximize rely on keyboard input which is not a very robust approach...

This Applescript seems to work without keyboard input ;-)

```
repeat
	try
		tell application "System Events" to tell process "Safari"
			set value of attribute "AXFullScreen" of window 1 to true
			exit repeat
		end tell
	end try
	delay 0.01
end repeat

```

> Can I know your MacOS characteristics (OS version, screen resolution, ...).

macos-type

For resolution:
```
#!/opt/local/bin/python3.9
# -*- coding: utf-8 -*-

import tkinter as tk
root=tk.Tk()
# Get screen width and height
ws=root.winfo_screenwidth();hs=root.winfo_screenheight()
print(f'{ws=} {hs=}\n') # => ws=1680 hs=1050

```

> If you have any Python knowledge, I would really appreciate if you can debug/investigate a little further... Unfortunately I don't have acces to a real MacOS and, as I said before, it was working OK on a virtualbox guest.

OK for Python, but it is a PyObjC, Applescript pb and unfortunately I am very busy :-(

Could you upload your "test_pygetwindow.py" log?

**Comment by Kalmat** [comment]
First of all, thank you so much for your time and your effort!!!

Apple does not "like" apps taking control of other apps... so, it does not provide many tools to do that (e.g. there is no way to access NSWindow Objects from "outside", which would give plenty of additional control options). Therefore, I had to rely on 
AppScript. It is not the best solution, but it's the only one I found! Furthermore, it's better to use "System Events", since not all apps have AppScript capabilities, or they need to be granted on Accessibility options (which is the case for the
piece of code you suggested!).

Right now, I can not understand why the code is not working on your computer. Maybe it is because of the MacOS version? I'm using High Sierra. I will try to set up a Catalina and Yosemite guests to check this.

The question is: PyGetWindow module is intended to control other apps, not exactly your own app. I could work on a version to control your own app, based on NSWindow Objects, but it would not fit the general "concept" of the module... what do you think?

This is my tests output, though it does not give much additional information.

MacBook-Pro-de-Kalma:tests kalma$ pytest -vv
=============================================== test session starts
===============================================
platform darwin -- Python 3.6.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 --
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
cachedir: .pytest_cache
rootdir: /Volumes/Proyectos/PycharmProjects/PyGetWindow
collected 1 item


test_pygetwindow.py::test_basic PASSED                                 [100%]

=============================================== 1 passed in 34.36s ================================================

Best Regards!

**Comment by macdeport** [comment]
> they need to be granted on Accessibility options (which is the case for the
piece of code you suggested!)

I need these Accessibility options for my Keyboard Maestro-based workflow.

What are the disadvantages of such options besides a possible more complex security issue?

> I could work on a version to control your own app, based on NSWindow Objects, but it would not fit the general "concept" of the module... what do you think?

An operative version based on NSWindow Objects would be very interesting.

> Right now, I can not understand why the code is not working on your computer.

How do I collect debug information that I can forward to you?

**Comment by Kalmat** [comment]
First off, I found why it does not work on Yosemite: there is no keyboard shortcut to maximize (fullscreen) a window!!!! HAHAHAHA!!! (installing Catalina right now).

Relying on AppScript has, IMO, some drawbacks:
- The final user of the script/program which uses the module, should enter Accessibility options and grant it. This user could not know how to do it, or even mistrust an app asking for privileges.
- The target app must have AppScript capabilities. Not all apps do have it (e.g. PyCharm does not!).

On the other hand, it has some advantages:
- I didn't find a solution without AppScript to move/resize a Window
- It seems to work with older versions (should we consider retro-compatibility for such older versions?)

Hard decissions at this point.

I'll try to work on an NSWindow version after holidays. Nevertheless, since Al is not responding, I am not sure how to continue, how it will integrate within the PyGetWindow module, and how it will eventually be available to other users/programmers... We will cross that bridge when we get to that river, right? ;)

I do really appreciate your help, dude!!!

**Comment by macdeport** [comment]
Thank you for your very sharp and informative summary of the situation... at the crossroads.

I hope your choice will be to continue developing a Python module for Mac OS X window management and if so count on my help, punctually at least ;-)

**Comment by Kalmat** [comment]
You really helped me a lot... to clarify my ideas and, way more important, with a boost of moral to continue (I was on the brink of giving up right before you two commented here).

I have finally surrended to evidences, so I think I will rely on AppleScript... I'm changing evrything now. I will be very short of time to work on this in the next few weeks, but I promise I will come back to you with a brand new version, and afterwards, I will start working on a NSWindow version.

This is a dark menace: Be sure I will count on you!!!! HAHAHAHAHAHA!

**Review by holychowders — COMMENTED** [review]
Everything in `src/pygetwindow/_pygetwindow_linux.py` seems to run perfectly fine on my Ubuntu machine. Good work!

**Comment by Kalmat** [comment]
So happy to hear that!!! Thank you!!!

**Comment by Kalmat** [comment]
Hi again!

As promissed, I have been working on a completely new version, based on AppleScript. Although it doesn't avoid the need to grant permissions on Accessibility options, it seems to work fine with all kind of apps (Terminal, TextEdit, Contacts, PyCharm, ...) in mono- and multi- window scenarios.

And, as promissed too, I have prepared an NSWindow version. I am not sure how to integrate both. For the moment I have added a new class (MacOSNSWindow) to the module (inside _pygetwindw_macos.py), which can be instantiated just passing the Application Object (NSApp). It works like a charm on Catalina!!!

So, if you are not the "owner" of the target app, you can use something like "pygetwindow.getActiveWindow()" or "pygetwindow.getWindowsWithTitle()" to manage the desired window using AppleScript. If you have the NSApp reference, then you can manage the window by using "pygetwindow.MacOSNSWindow(NSApp)" (you still have the option to use "pygetwindow.getActiveWindow(NSApp)" or "pygetwindow.getWindowsWithTitle(NSApp)" methods) . They both share all methods and properties.

You can find the code here: https://github.com/Kalmat/PyGetWindow

Use "pytest -vv test_pygetwindow.py" to test the AppleScript version
Use "python3 test_MacNSWindow.py" to test the NSWindow version

If you have the time to test, please let me know about the results, comments, anything...

Thank you!

**Comment by macdeport** [comment]
Here are the requested tests:

test_pygetwindow py-210901

test_MacNSWindow py-210901

You are welcome...

**Comment by Kalmat** [comment]
Thank you! and sorry for the inconveniences. That is... unexpected.

I guess something wrong is happening when importing the pygetwindow module.  It could fail somehow when executing the methods and properties, but the problem seems to be that it is just not finding the methods (note getAllWindows() is outside the class, directly accessible within the module). 

To be sure it is importing the right code, and of course if you have the time, we can try a quick solution. Please, run this on the Terminal before passing the tests again:
`
export PYTHONPATH=/Users/alain/Documents/Logiciels/Developpement/tkinter/pyautogui/PyGetWindow-master/:$PYTHONPATH
`
(I have copied the path to the module folder from your screenshot, please verify it is correct)

Thank you so much again!!!

**Comment by macdeport** [comment]
Unfortunately (at first glance) no change in results:
test_pygetwindow py-210902

test_MacNSWindow py-210902

Thanks for your efforts :-)

PS: BTW from what country are you?

**Comment by Kalmat** [comment]
Completely lost now... I can't figure out what can be causing that behavior on your system (or on mine), and worst, I don't exactly know what to do to debug it   :(

I have successfully tested everything on High Sierra and Catalina, both on virtualbox VMs. I will try to borrow a real mac from a friend to test and debug (I think it will be hard to find a Yosemite version anyway).

I am attaching a .zip with three modified files in which I have inserted some "miserable" print statements while I think/get something better, If you can please unzip them on the PyGetWindow main folder (PyGetWindow-master in your case) and test again
, I would really appreciate it. By the moment, run only "python3 test_MacNSWindow", and please run the "export" command before that.

PS: Please, don't tell me that my English doesn't seem to be native!!!! (HAHAHAHAHA! Just kidding! I am from Spain)

[PyGetWindow.zip](https://github.com/asweigart/PyGetWindow/files/7099934/PyGetWindow.zip)

EDIT: I have made a complete fresh install of a High Sierra VM. I have installed only Python 3.9 and the required modules using pip (pyobjc, pyrect and pytest exclusively). Both tests work perfect!!! I will have a real mac this weekend, so I will be able to test and debug. Honestly, I think it will work fine as well... we will see. If this is the case, perhaps Yosemite or something previously installed on your machine could be the cause?

**Comment by macdeport** [comment]
1. your tests:

test_MacNSWindow py-210903

2. Useless Python cache (9.1Mb) in tests (PyGetWindow.zip) as it is created:

PyGetWindow-210902-170519 zip

3. To improve perhaps our raw tracking, display:
```python
#------------------------------------------------
def debug_print_no(*msg,offset=(0,1),**keywords):
	"""Print() with lineno for debug
	
	offset[0]  rank of 1st code line to display. 0 is end of debug_print_no() 
	           statement.
	offset[1]  number of code line to display.
	(08/03/19)
	"""
	# https://docs.python.org/3.6/library/inspect.html#inspect.currentframe
	from inspect import currentframe
	# https://docs.python.org/3.6/library/linecache.html
	from linecache import getline
	
	frame = currentframe().f_back;filep=frame.f_code.co_filename
	lineno=frame.f_lineno
	print('>>File "'+filep+'", line',str(lineno+offset[0])+':')
	name='>>'+frame.f_code.co_name;name=name if name[-1]=='>' else name+'()'
	print(name)
	for i in range(lineno+offset[0],lineno+offset[0]+offset[1]):
		print(getline(filep,i),end='')
	print(*msg, **keywords)
	return() # debug_print_no()
```
For what Python version range we are suppose to code? Use of https://docs.python.org/3.9/library/string.html#format-string-syntax is also very handy

**Comment by Kalmat** [comment]
Thank YOU for your efforts and HELP!!!!!

1. MY f***g FAULT! The RIGHT export sentence is:
`export PYTHONPATH=/Users/alain/Documents/Logiciels/Developpement/tkinter/pyautogui/PyGetWindow-master/src/:$PYTHONPATH
`
I bet this should solve the problem. I am now testing on the "real" Mac I borrowed from a friend for this weekend, one which never had Python nor similar, and everything works fine... It's a High Sierra, not Yosemite. I could not get a Yosemite Mac yet.

2. I had never seen that piece of code... I should replace the "print()" statements by that, right? If so, and in case point 1 doesn't solve the issue, I will prepare a new version using it. Thank you again!

3. It should work for all Python 3.x versions. The module was initially intended to be compatible with 2.x versions too, but I think it is not worth now. I tested my code with a number of different 3.x versions but, to be honest, since your tests failed, I have mainly focused on get it working, more than assuring compatibility and such. Anyway, I will take a look to that link you are sending.

You are really helping me a lot!!!

**Comment by macdeport** [comment]
[test_MacNSWindow.py.zip](https://github.com/asweigart/PyGetWindow/files/7108690/test_MacNSWindow.py.zip)

test_MacNSWindow py-210904

**Comment by macdeport** [comment]
Workaround for path jam...!

folder-tree

New version 'test_MacNSWindow.py-210904-2':

[test_MacNSWindow.py.zip](https://github.com/asweigart/PyGetWindow/files/7109417/test_MacNSWindow.py.zip)

test_MacNSWindow py-210904-2

Cheers

**Comment by Kalmat** [comment]
This is completely different!!! So sorry for my previous error about the export sentence. I omitted "/src/"...

I have seen you modified test_MacNSWindow including that new debug method. Thank you! (I will use it in future developments). The problem now I guess it is you are invoking:

`self.npw = pygetwindow.getActiveWindow() # <= is a string!`

but this is for the Apple Script version (managing other apps). For NSWindow version you have to pass the NSApp() object:

`self.npw = pygetwindow.getActiveWindow(NSApp())`

Anyway, the first sentence should work as well. I will definitely have to get a Yosemite install and "play" with it...  I suspect there are some relevant changes in AppScript and Cocoa since that version.

EDIT: ...or maybe you have to grant Accessibility permissions to Terminal app and / or  Python in order to allow the script to handle other apps? (This is not required for the NSWindow version)

**Comment by Kalmat** [comment]
Hi again! I finally managed to install Yosemite (well, it's a Hackintosh because I couldn't find anything else, and it's on virtualbox). NSWindow works perfect too!!! However, AppScript version doesn't. I am executing the scripts directly from the terminal and nothing happens... it doesn't fail, but it has no effect. I will keep on investigating.

No offense, but: should we maintain compatibility with such older versions? From which version do you thin it would be reasonable?

**Comment by Kalmat** [comment]
Hi again! I finally managed to install Yosemite (well, it's a Hackintosh because I couldn't find anything else, and it's on virtualbox). NSWindow version works perfect! However, maximize is not working on AppleScript version (it doesn't fail, but it has no effect. So, I had to turn Maximize into Zoom (I believe it's reasonable),

I'm attaching a new version so you can help me to test if you have the time and the will. Without any obligation, of course! If everyting works, I will prepare a new version including all these macOS versions. Thank YOU!!!

[PyGetWindow.zip](https://github.com/asweigart/PyGetWindow/files/7129223/PyGetWindow.zip)

**Comment by macdeport** [comment]
The impressive fruit of your determined efforts...
Complementary and synergistic to pyautogui.

test_MacNSWindow py-210908

You are welcome

**Comment by Kalmat** [comment]
THANK YOU!!!! Very good news! You can also run "pytest -vv test_pygetwindow.py"... It should work now.

I have already prepared a version containing both behaviors: Zoom for Yosemite and Maximize for all the rest (now I must get El Capitan and Sierra distros to check).

Anyway, the author is not responding (though he modified the original repo a few days ago)... I will propose him to make a fork and publish separately it in case he's not interested, but I really prefer the first option: merge.

Back to your suggestion now that everything is working, I took a look to the link you attached. Don't you like the use of "%" to pass parameters to a string? or are you concerned with retro-compatibility? If I am not wrong, this could be an issue on Python 2.5 and below, right? And, furthermore, do you think this should be 2.x compatible? Since it doesn't have support any more, I have strong doubts, sincerely.

I think I will close this PR and will open a new one... Let's see if we are lucky this time.

**Comment by macdeport** [comment]
test_pygetwindow py-210909

Passed the logged test :-)

Nevertheless the window is many times outside the physical limits of the screen on the left: is this the intended behavior? (no information on the actual desired position)

**Comment by Kalmat** [comment]
YUHUUUUU!!!! Well, all seems to be working fine now. I can rest for a while (a couple of hours... HAHAHA!).

Yes, it was the intended behavior to check if there was some limitations (e.g. on Linux you can not pass coordinates outside the screen). The desired and the actual position/size is implicitly controlled by the "assert" sentences, so everything should be ok.

Can I ask what do you think about Python 2 support, Yosemite support (or how many versions behind from current it would be reasonable), the use of "%" to pass parameters, the situation with the PR, and (this is specially optional to respond) why did you ask my nationality (just curious, not a problem at all)?

Thanks a LOT!!!!!!!

EDIT: I forgot to say not all on Apple Script are advantages. With my previous version (which turned out to be incomplete), you were sure that you were addressing the desired window (using "kCGWindowNumber" key). On Apple Script, it is not possible (or I couldn't find a way, though I tried to use "id"). So we have to rely on the window name, which is not 100% trustable. Furthermore, Apple decided to suppress the name ("kCGWindowName" key) from the windows info list objects.

**Comment by macdeport** [comment]
The link is https://docs.python.org/3.9/library/string.html#format-string-syntax (if I am right) just with a recall of
 the handy new format syntax since Python 3.6

new-format-string-syntax

without %

**Comment by macdeport** [comment]
> Can I ask what do you think about
● Python 2 support

Current Python versions (Python.org)
python-versions
No idea of potential number of PyGetWindow users still using Python 2; is it difficult to keep compatibility?
If so, maybe disable Python 2 and wait for a potential user to show up ;-)

> ● Yosemite support (or how many versions behind from current it would be reasonable) at present at least one user: myself ;-)
BTW I've been thinking about your clever "Maximize" <= "Zoom" workaround: perhaps a more sophisticated solution is even possible... Get the dimensions of the "Maximized" window (if possible), then Zoom it, then Resize it

> ● the use of "%" to pass parameters

I don't understand: could you elaborate?

> ● the situation with the PR

Hoping for its answer... if not ask the GitHub support about a (quite) good solution.

> ● why did you ask my nationality?

This is just a friendly and anecdotal curiosity as your country is not indicated in your profile and with practical repercussion concerning the adjustment of personal rhythms: we are neighbor.

**Comment by macdeport** [comment]
https://github.com/asweigart/PyGetWindow/pull/42#issuecomment-916011040

About AppleScript: Of course I suggest to use NSWindow as much as possible and to use AppleScript only as a workaround because Apple does not really support it...

**Comment by Kalmat** [comment]
> No idea of potential number of PyGetWindow users still using Python 2; is it difficult to keep compatibility?
If so, maybe disable Python 2 and wait for a potential user to show up ;-)

About 2.7, it says " end-of-life". Anyway, not so difficult to maintain, though it doubles test efforts. Just wondering if it is worth. I will give it a try to decide.

> I don't understand: could you elaborate?

I was referring to the use of "%" to pass parameters to strings, since I thought you were propposing to change that by str.format()

> Hoping for its answer... if not ask the GitHub support about a (quite) good solution.

I will. I'm closing this PR to open a new "clean" one with all this new code, right after I finish testing the whole thing in several OS versions. Let's hope Al is responding or, otherwise, I will ask GitHub. Thank you for your advice.

> This is just a friendly and anecdotal curiosity as your country is not indicated in your profile and with practical repercussion concerning the adjustment of personal rhythms: we are neighbor.

HAHAHAHA! Right!

> About AppleScript: Of course I suggest to use NSWindow as much as possible and to use AppleScript only as a workaround because Apple does not really support it...

Totally agree. I have finally managed to address the desired window, using a workaround based on kCGWindowNumber property when available (it is in almost all cases). It should work fine now in most use cases, though Apple Script still has some relevant drawbacks. The NSWindow part works like a charm!!!!!

Thank you again. Really helpful and encouraging.

**Comment by macdeport** [comment]
@Kalmat Since Al answers for pyautogui we can have some hope of an answer for PyGetWindow ;-)
https://github.com/asweigart/pyautogui/issues/616#issuecomment-918853962

**Comment by Kalmat** [comment]
Fingers crossed.... Thank YOU again!!!

I have tested the script on Python 2.7 and works perfectly fine! I am closing this PR to open a new, "clean" one... or should I just commit last changes? What's your opinion?

EDIT: Sorry, I forgot to comment. I tried your workaround Zoom --> Resize, but didn't work. Once zoomed, the window doesn't seem to admit resizing!

**Comment by macdeport** [comment]
Since the game in the sandbox seems to be over, maybe we can close this RP ;-) and thus make a clean, global commit as you proposed, listing the synthesis of the many contributions :-)

Maybe have a usable version on your branch, until Al's reaction.

It seems good to connect PyGetWindow <=> PyAutoGui by cross-referencing in each other's documentation.

For example:
https://pyautogui.readthedocs.io/en/latest/roadmap.html

floating-screenshot-172456


which is more or less PyGetWindow...

**Comment by Kalmat** [comment]
Hi, macdeport!

I don't know if you still can receive this mail (there is no e-mail in your
profile). I eventually deleted the PR and the repository. I just wanted you
to know because of your interest. As my profile states, I code just for
fun... and this stopped to be fun a long ago. I have to admit this has been
more demotivating than I expected. However, because of your support (from
you and holychowders) I decided to upload other repositories that I had,
just to share the whole thing or pieces which may be useful for others. I
hope you have the time to check them and find them useful or interesting.
If so, let me know any comments you might have.

Thanks for your help! Kind regards.

**Comment by macdeport** [comment]
I am very sorry that you did not get a response... but at least you get floating-screenshot-102250

Personally I am still interested in using what you have generously done.

This is in fact a private conversation and it is perhaps best to use our personal addresses.

For some privacy:
https://github.com/jbarlow83/OCRmyPDF/wiki

But I have never used and it is interesting to explore if you agree.

**Comment by Kalmat** [comment]
Nah, don't worry... Moving forward now.

Are you aware that one of my repositories is called "ezCrypto" and it is
intended to cypher messages, files and even can produce or read QRs?
HAHAHAHAHA! Just kidding. My module needs a common token (a key or a
password) to be known by both peers, not suitable in this case, but maybe
interesting for you in other scenarios. I have used GPG in the past, but
it's been a long time since then. I have read the link you attached, and it
seems to rely on the "key used to commit"... Do you know where I can find
my github public key? If not, we can generate a new private-public key pair
using GPG too (
https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
)

Another alternative that I suggest to you for this and many other cases, is
to open a new gmail account, only for things you don't trust. For instance,
my ***@***.***" account is intended for that, this is why I feel
comfortable publishing it.

Best!

**Comment by Kalmat** [comment]
Hi there!

I  finally decided to open a new fork, but I will not open any PR to the
original project. I contacted GitHub as you suggested but, appart from some
tips on licensing, they didn't give me a definitive answer (it is quite
rational, on the other hand). So you can fork it, download it, use it, test
it... or whatever you want. In addition to that, if you find any issue or
you have any suggestion or idea, it is more than welcome!

Best regards,

PS: I included your user name on the readme and contributors files. I hope
you don't mind. You were really helpful. Do you know if there is any other
way to add a "recognition" or similar?

**Comment by Kalmat** [comment]
Sorry, I forgot. You can use this address to answer me in case you don't
want to keep on using this thread (unfortunately, I don't have yours)

Good weekend!

**Pull request closed without merging**
